name: Docker Image CI

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fipanganiban/bantay:latest
    - uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: fipanganiban/bantay
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
